---
- name: Configure Filebeat
  become: true
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
    mode: 0644
- name: Set filebeat systemwork
  become: true
  command:
    cmd: filebeat modules enable system nginx mysql
    chdir: /usr/share/filebeat/bin
  register: filebeat_modules
  changed_when: filebeat_modules.stdout != 'Module system is already enabled'